### ISSUE TITLE
Anyone home?

### ISSUE THREAD

**Issue by AaronFeller** [fergaljd/cyclops#1]
I'm interested in using these scripts and was going to do some cleaning of the formatting. Will someone be able to accept a pull request? I'd like to give credit here, rather than just republishing the scripts in a new repository under my name.

Happy to be added as a contributor as well if that's easier.

Thanks!

**Comment by fergaljd** [comment]
Hi Aaron,

I'd accept a pull request, and I'm happy to add you as a contributor. It's
been a long time since I looked at the code so I'd be pleased if someone
else can make use of it.

Fergal

**Comment by AaronFeller** [comment]
Closed as complete.
